BOOLEAN_EXPRESSION -> BOOLEAN_EXPRESSION or BOOLEAN_TERM
BOOLEAN_EXPRESSION -> BOOLEAN_TERM
BOOLEAN_TERM -> BOOLEAN_TERM and BOOLEAN_FACTOR
BOOLEAN_TERM -> BOOLEAN_FACTOR
BOOLEAN_FACTOR -> ( BOOLEAN_EXPRESSION )
BOOLEAN_FACTOR -> id
BOOLEAN_FACTOR -> MATH_EXPRESSION < MATH_EXPRESSION
BOOLEAN_FACTOR -> MATH_EXPRESSION <= MATH_EXPRESSION
BOOLEAN_FACTOR -> MATH_EXPRESSION != MATH_EXPRESSION
BOOLEAN_FACTOR -> MATH_EXPRESSION >= MATH_EXPRESSION
BOOLEAN_FACTOR -> MATH_EXPRESSION == MATH_EXPRESSION
BOOLEAN_FACTOR -> MATH_EXPRESSION > MATH_EXPRESSION
MATH_EXPRESSION -> MATH_EXPRESSION + MATH_TERM
MATH_EXPRESSION -> MATH_TERM
MATH_TERM -> MATH_TERM * MATH_FACTOR
MATH_TERM -> MATH_FACTOR
MATH_FACTOR -> ( MATH_EXPRESSION )
MATH_FACTOR -> id




BOOLEAN_EXPRESSION -> BOOLEAN_EXPRESSION or BOOLEAN_TERM
BOOLEAN_EXPRESSION -> BOOLEAN_TERM

BOOLEAN_TERM -> BOOLEAN_TERM and BOOLEAN_FACTOR
BOOLEAN_TERM -> BOOLEAN_FACTOR

BOOLEAN_FACTOR -> id
BOOLEAN_FACTOR -> not BOOLEAN_FACTOR
BOOLEAN_FACTOR -> ( BOOLEAN_EXPRESSION )
BOOLEAN_FACTOR -> RELATION_EXPRESSION

RELATION_EXPRESSION -> id == id
RELATION_EXPRESSION -> id != id
RELATION_EXPRESSION -> id < id
RELATION_EXPRESSION -> id <= id
RELATION_EXPRESSION -> id >= id
RELATION_EXPRESSION -> id > id

RELATION_EXPRESSION -> id




























# BOOLEAN_EXPRESSION -> @push identifier

BOOLEAN_EXPRESSION -> BOOLEAN_TERM BOOLEAN_EXPRESSION2
BOOLEAN_EXPRESSION2 -> or BOOLEAN_TERM BOOLEAN_EXPRESSION2
BOOLEAN_EXPRESSION2 -> ''
BOOLEAN_TERM -> BOOLEAN_FACTOR BOOLEAN_TERM2
BOOLEAN_TERM2 -> and BOOLEAN_FACTOR BOOLEAN_TERM2
BOOLEAN_TERM2 -> ''
BOOLEAN_FACTOR -> id
BOOLEAN_FACTOR -> ( BOOLEAN_EXPRESSION )
BOOLEAN_FACTOR -> not BOOLEAN_FACTOR
BOOLEAN_FACTOR -> true
BOOLEAN_FACTOR -> false
BOOLEAN_FACTOR -> MATH_EXPRESSION BOOLEAN_FACTOR2
BOOLEAN_FACTOR2 -> COMPARISON_OPERATOR MATH_EXPRESSION
BOOLEAN_FACTOR2 -> ''