MATH_EXPRESSION -> MATH_TERM MATH_EXPRESSION2

MATH_EXPRESSION2 -> + MATH_TERM MATH_EXPRESSION2
MATH_EXPRESSION2 -> nil

MATH_TERM -> MATH_FACTOR MATH_TERM2
MATH_TERM2 -> * MATH_FACTOR MATH_TERM2 
MATH_TERM2 -> / MATH_FACTOR MATH_TERM2 
MATH_TERM2 -> nil

MATH_FACTOR -> identifier
MATH_FACTOR -> ( MATH_EXPRESSION )
MATH_FACTOR -> number
MATH_FACTOR -> identifier [ MATH_EXPRESSION ]



BOOLEAN_EXPRESSION -> BOOLEAN_TERM BOOLEAN_EXPRESSION2
BOOLEAN_EXPRESSION2 -> or BOOLEAN_TERM BOOLEAN_EXPRESSION2
BOOLEAN_EXPRESSION2 -> nil

BOOLEAN_TERM -> BOOLEAN_FACTOR BOOLEAN_TERM2
BOOLEAN_TERM2 -> and BOOLEAN_FACTOR BOOLEAN_TERM2
BOOLEAN_TERM2 -> nil

BOOLEAN_FACTOR -> identifier
BOOLEAN_FACTOR -> ( BOOLEAN_EXPRESSION )
BOOLEAN_FACTOR -> MATH_EXPRESSION < MATH_EXPRESSION
BOOLEAN_FACTOR -> MATH_EXPRESSION <= MATH_EXPRESSION
BOOLEAN_FACTOR -> MATH_EXPRESSION > MATH_EXPRESSION
BOOLEAN_FACTOR -> MATH_EXPRESSION >= MATH_EXPRESSION
BOOLEAN_FACTOR -> MATH_EXPRESSION == MATH_EXPRESSION
BOOLEAN_FACTOR -> MATH_EXPRESSION != MATH_EXPRESSION

PROGRAM -> int main ( ) { STATEMENT_LANGUAGE }
STATEMENT_LANGUAGE -> STATEMENT STATEMENT_LANGUAGE
STATEMENT_LANGUAGE -> STATEMENT
STATEMENT -> IF_STATEMENT
STATEMENT -> WHILE_STATEMENT
STATEMENT -> DO_WHILE_STATEMENT
STATEMENT -> FOR_STATEMENT
STATEMENT -> ASSIGNMENT_STATEMENT
STATEMENT -> DECLARATION_STATEMENT

ASSIGNMENT_STATEMENT -> identifier = MATH_EXPRESSION ASSIGNMENT_STATEMENT2
ASSIGNMENT_STATEMENT2 -> ;
ASSIGNMENT_STATEMENT2 -> < MATH_EXPRESSION ;
ASSIGNMENT_STATEMENT2 -> > MATH_EXPRESSION ;
ASSIGNMENT_STATEMENT2 -> == MATH_EXPRESSION ;
ASSIGNMENT_STATEMENT2 -> != MATH_EXPRESSION ;
ASSIGNMENT_STATEMENT2 -> >= MATH_EXPRESSION ;
ASSIGNMENT_STATEMENT2 -> <= MATH_EXPRESSION ;

IF_STATEMENT -> if ( BOOLEAN_EXPRESSION ) STATEMENT IF_STATEMENT2
IF_STATEMENT -> if ( BOOLEAN_EXPRESSION ) { STATEMENT_LANGUAGE } IF_STATEMENT2
IF_STATEMENT2 -> nil
IF_STATEMENT2 -> else STATEMENT
IF_STATEMENT2 -> else { STATEMENT_LANGUAGE }

WHILE_STATEMENT -> while ( BOOLEAN_EXPRESSION ) { STATEMENT_LANGUAGE }
WHILE_STATEMENT -> while ( BOOLEAN_EXPRESSION ) STATEMENT
DO_WHILE_STATEMENT -> do { STATEMENT_LANGUAGE } while ( BOOLEAN_EXPRESSION )
FOR_STATEMENT -> for ( SIMPLE_ASSIGNMENT_STATEMENT ; BOOLEAN_EXPRESSION ; ICREAMENT_DECREAMENT_STATEMENT )

SIMPLE_ASSIGNMENT_STATEMENT -> identifier = number
ICREAMENT_DECREAMENT_STATEMENT -> identifier ++
ICREAMENT_DECREAMENT_STATEMENT -> identifier --

STATEMENT_LANGUAGE -> STATEMENT STATEMENT_LANGUAGE2
STATEMENT_LANGUAGE2 -> nil
STATEMENT_LANGUAGE2 -> STATEMENT STATEMENT_LANGUAGE2

TYPE -> float
TYPE -> int
TYPE -> char
TYPE -> double
TYPE -> bool

DECLARATION_STATEMENT -> TYPE identifier DECLARATION_STATEMENT2
DECLARATION_STATEMENT2 -> ;
DECLARATION_STATEMENT2 -> , identifier DECLARATION_STATEMENT2

DECLARATION_STATEMENT2 -> = number ;
DECLARATION_STATEMENT2 -> = number DECLARATION_STATEMENT2
DECLARATION_STATEMENT2 -> = number DECLARATION_STATEMENT2
DECLARATION_STATEMENT2 -> [ number ] DECLARATION_STATEMENT2

DECLARATION_STATEMENT -> TYPE identifier [ ] = { number DECLARATION_STATEMENT2
DECLARATION_STATEMENT2 -> , number DECLARATION_STATEMENT2
DECLARATION_STATEMENT2 -> }

DECLARATION_STATEMENT -> * identifier DECLARATION_STATEMENT2
DECLARATION_STATEMENT2 -> * identifier DECLARATION_STATEMENT2
DECLARATION_STATEMENT2 -> ;
